# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/resqnet_db
spring.datasource.username=postgres
spring.datasource.password=Alaminhossainrifat@015
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App name
spring.application.name=resqnet-backend

# JWT
jwt.secret=resqnet_super_secret_key_2026_very_long_string
jwt.expiration=86400000

#API
api.tomtom.key=EaFLLtCW0g6LQna11du2uHRU5K028wjb
api.weather.key=6ff405342a39d58e25262d5a1ac93bfa